openapi: 3.0.0
info:
  title: Books API
  description: API para gerenciar livros
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /books:
    get:
      summary: Retorna todos os livros
      responses:
        '200':
          description: Lista de livros
    post:
      summary: Cria um novo livro
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Livro criado
  /books/{id}:
    get:
      summary: Retorna um livro por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes do livro
    put:
      summary: Atualiza um livro por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Livro atualizado
    delete:
      summary: Deleta um livro por ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Livro deletado
components:
  schemas:
    Book:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        price:
          type: number